### ISSUE TITLE
Toto neni pexeso...

### ISSUE THREAD

**Issue by MartinRostejnsky** [adeladitrichova/Pexeso#3]
Pexeso vypada jinak 😿

**Comment by adeladitrichova** [comment]
Dobrý den,

Děkuji vám za vaši zprávu na repozitáři na GitHubu. Chápu, že jste vyjádřil názor, že repozitář se sice jmenuje "Pexeso", ale přesto to není skutečná implementace hry Pexeso. Rád bych vám vysvětlil situaci.

Repozitář, na který jste narazil, nese název "Pexeso", ale ve skutečnosti neobsahuje implementaci hry Pexeso, jak jste očekával. Možná to může být zdrojem nedorozumění, že medvědi nevědí, až jste zjistil, že jeho obsah nesouvisí s touto konkrétní hrou.

Je důležité si uvědomit, že názvy repozitářů na GitHubu mohou být voleny různými způsoby a ne vždy přesně odrážejí jejich obsah. Je možné, že autor repozitáře měl důvody, které vedly k volbě názvu "Pexeso", který může být spojen s jiným projektem nebo konceptem.

Pokud jste skutečně hledal implementaci hry Pexeso, doporučuji vám prozkoumat další zdroje, kde byste mohl najít požadovaný kód. Existuje mnoho tutoriálů a příkladů implementace hry Pexeso v různých programovacích jazycích.

**Comment by adeladitrichova** [comment]
![obrazek](https://github.com/adeladitrichova/Pexeso/assets/91247571/f883c44a-bf19-4c41-b12a-e79dbdd89278)

**Comment by adeladitrichova** [comment]
![obrazek](https://github.com/adeladitrichova/Pexeso/assets/91247571/63b6f6ec-7f64-45f4-a8b0-f518485baa83)
